export const ERROR_CODES = {
  // ─── Auth & Account State ────────────────────────────────────────────────────
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  PHONE_ALREADY_IN_USE: 'PHONE_ALREADY_IN_USE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',

  // ─── OTP & 2FA ───────────────────────────────────────────────────────────────
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  INVALID_OTP_SESSION: 'INVALID_OTP_SESSION',
  USER_ID_REQUIRED: 'USER_ID_REQUIRED',
  OTP_RATE_LIMIT_EXCEEDED: 'OTP_RATE_LIMIT_EXCEEDED',
  TWO_FACTOR_NOT_ENABLED: 'TWO_FACTOR_NOT_ENABLED',
  TWO_FACTOR_ALREADY_ENABLED: 'TWO_FACTOR_ALREADY_ENABLED',
  TWO_FACTOR_ALREADY_DISABLED: 'TWO_FACTOR_ALREADY_DISABLED',

  // ─── Verification Links & Tokens ─────────────────────────────────────────────
  INVALID_VERIFICATION_LINK: 'INVALID_VERIFICATION_LINK',
  LINK_ALREADY_USED: 'LINK_ALREADY_USED',
  LINK_EXPIRED: 'LINK_EXPIRED',
  INVALID_OR_EXPIRED_REGISTRATION_COMPLETION_TOKEN:
    'INVALID_OR_EXPIRED_REGISTRATION_COMPLETION_TOKEN',
  INVALID_SESSION_ID: 'INVALID_SESSION_ID',
  RESUME_REGISTRATION_COMPLETION: 'RESUME_REGISTRATION_COMPLETION',

  // ─── Refresh Tokens ──────────────────────────────────────────────────────────
  TOKEN_REUSE: 'TOKEN_REUSE',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_NOT_FOUND: 'REFRESH_TOKEN_NOT_FOUND',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',

  // ─── Registration Flow ───────────────────────────────────────────────────────
  REGISTRATION_RATE_LIMIT_EXCEEDED: 'REGISTRATION_RATE_LIMIT_EXCEEDED',
  REGISTRATION_ALREADY_COMPLETED: 'REGISTRATION_ALREADY_COMPLETED',
  REGISTRATION_NOT_INITIATED: 'REGISTRATION_NOT_INITIATED',

  // ─── Rate Limiting ───────────────────────────────────────────────────────────
  TOO_MANY_AUTH_REQUESTS: 'TOO_MANY_AUTH_REQUESTS',
  TOO_MANY_REGISTRATION_REQUESTS: 'TOO_MANY_REGISTRATION_REQUESTS',
  TOO_MANY_REFRESH_REQUESTS: 'TOO_MANY_REFRESH_REQUESTS',
  RESEND_COOLDOWN_ACTIVE: 'RESEND_COOLDOWN_ACTIVE',
  TOO_MANY_RESEND_REQUESTS: 'TOO_MANY_RESEND_REQUESTS',

  // ─── General ─────────────────────────────────────────────────────────────────
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
