export const LOGIN_RESPONSE_CODE = {
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  OTP_REQUIRED: 'OTP_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',
} as const;

export const LOGIN_OTP_RESPONSE_CODE = {
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_VERIFIED: 'OTP_VERIFIED',
  TOO_MANY_AUTH_REQUESTS: 'TOO_MANY_AUTH_REQUESTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const;

export const RESEND_LOGIN_OTP_RESPONSE_CODE = {
  INVALID_OTP_SESSION: 'INVALID_OTP_SESSION',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  TWO_FACTOR_NOT_ENABLED: 'TWO_FACTOR_NOT_ENABLED',
  OTP_RATE_LIMIT_EXCEEDED: 'OTP_RATE_LIMIT_EXCEEDED',
  OTP_RESENT: 'OTP_RESENT',
} as const;

export const LOGOUT_RESPONSE_CODE = {
  INVALID_SESSION_ID: 'INVALID_SESSION_ID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
} as const;


// Registration 

export const INITIATE_REGISTRATION_RESPONSE_CODE = {
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  REGISTRATION_RATE_LIMIT_EXCEEDED: 'REGISTRATION_RATE_LIMIT_EXCEEDED',
  TOO_MANY_REGISTRATION_REQUESTS: 'TOO_MANY_REGISTRATION_REQUESTS',
  REGISTRATION_INITIATED: 'REGISTRATION_INITIATED',
} as const;

export const VERIFY_EMAIL_RESPONSE_CODE = {
  INVALID_VERIFICATION_LINK: 'INVALID_VERIFICATION_LINK',
  LINK_ALREADY_USED: 'LINK_ALREADY_USED',
  TOO_MANY_AUTH_REQUESTS: 'TOO_MANY_AUTH_REQUESTS',
  RESUME_REGISTRATION_COMPLETION: 'RESUME_REGISTRATION_COMPLETION',
  REGISTRATION_ALREADY_COMPLETED: 'REGISTRATION_ALREADY_COMPLETED',
  LINK_EXPIRED: 'LINK_EXPIRED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
} as const;